2011-10-06 21:36:39,034 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','Pt' exists
2011-10-06 21:36:39,056 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','Pt'
2011-10-06 21:36:39,056 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','Ag' exists
2011-10-06 21:36:39,084 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','Ag'
2011-10-06 21:36:39,085 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','H' exists
2011-10-06 21:36:39,085 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','H'
2011-10-06 21:36:39,086 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','Al' exists
2011-10-06 21:36:39,087 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','Al'
2011-10-06 21:36:39,087 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','O' exists
2011-10-06 21:36:39,088 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','O'
2011-10-06 21:36:39,089 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','N' exists
2011-10-06 21:36:39,089 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','N'
2011-10-06 21:36:39,090 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','Au' exists
2011-10-06 21:36:39,091 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','Au'
2011-10-06 21:36:39,091 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','Pd' exists
2011-10-06 21:36:39,092 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','Pd'
2011-10-06 21:36:39,093 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants','EMT','Cu' exists
2011-10-06 21:36:39,093 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCElasticConstants','EMT','Cu'
2011-10-06 21:36:39,094 - openkimtests.pipeline.run_tests - INFO - Potential 'EMT' run took 0.06311321258544922 seconds
2011-10-06 21:36:39,094 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MLJ_CLUSTER_F90'
2011-10-06 21:36:39,094 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:39,095 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCElasticConstants',potential='model_Ar_P_MLJ_CLUSTER_F90',element='Ar'
2011-10-06 21:36:39,095 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,095 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,096 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCLattice',potential='model_Ar_P_MLJ_CLUSTER_F90',element='Ar'
2011-10-06 21:36:39,096 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,097 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,097 - openkimtests.Test.FCCLattice - DEBUG - Recieved a main method call
2011-10-06 21:36:39,097 - openkimtests.Test.FCCLattice - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,098 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,098 - openkimtests.potential - DEBUG - potentialname: model_Ar_P_MLJ_CLUSTER_F90 found
2011-10-06 21:36:39,098 - openkimtests.potential - DEBUG - element 'Ar' found
2011-10-06 21:36:39,170 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCElasticConstants', potential='model_Ar_P_MLJ_CLUSTER_F90', element='Ar', info:UnboundLocalError("local variable 'testObject' referenced before assignment",)
2011-10-06 21:36:39,171 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 56, in run_test
    del testObject
UnboundLocalError: local variable 'testObject' referenced before assignment

2011-10-06 21:36:39,171 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.07684206962585449 seconds
2011-10-06 21:36:39,172 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MLJ_CLUSTER_F90' run took 0.07731914520263672 seconds
2011-10-06 21:36:39,172 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MLJ_NEIGH_RVEC_F'
2011-10-06 21:36:39,172 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:39,173 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCElasticConstants',potential='model_Ar_P_MLJ_NEIGH_RVEC_F',element='Ar'
2011-10-06 21:36:39,173 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,173 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,174 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCLattice',potential='model_Ar_P_MLJ_NEIGH_RVEC_F',element='Ar'
2011-10-06 21:36:39,174 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,175 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,175 - openkimtests.Test.FCCLattice - DEBUG - Recieved a main method call
2011-10-06 21:36:39,176 - openkimtests.Test.FCCLattice - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,176 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,176 - openkimtests.potential - DEBUG - potentialname: model_Ar_P_MLJ_NEIGH_RVEC_F found
2011-10-06 21:36:39,176 - openkimtests.potential - DEBUG - element 'Ar' found
2011-10-06 21:36:39,243 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCElasticConstants', potential='model_Ar_P_MLJ_NEIGH_RVEC_F', element='Ar', info:UnboundLocalError("local variable 'testObject' referenced before assignment",)
2011-10-06 21:36:39,244 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 56, in run_test
    del testObject
UnboundLocalError: local variable 'testObject' referenced before assignment

2011-10-06 21:36:39,245 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.07234001159667969 seconds
2011-10-06 21:36:39,245 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MLJ_NEIGH_RVEC_F' run took 0.07276797294616699 seconds
2011-10-06 21:36:39,245 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_ArNe_P_MLJ_NEIGH_RVEC_F'
2011-10-06 21:36:39,246 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:39,246 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCElasticConstants',potential='model_ArNe_P_MLJ_NEIGH_RVEC_F',element='Ar'
2011-10-06 21:36:39,246 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,247 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,247 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCLattice',potential='model_ArNe_P_MLJ_NEIGH_RVEC_F',element='Ar'
2011-10-06 21:36:39,248 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,248 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,249 - openkimtests.Test.FCCLattice - DEBUG - Recieved a main method call
2011-10-06 21:36:39,249 - openkimtests.Test.FCCLattice - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,249 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,249 - openkimtests.potential - DEBUG - potentialname: model_ArNe_P_MLJ_NEIGH_RVEC_F found
2011-10-06 21:36:39,250 - openkimtests.potential - DEBUG - element 'Ar' found
2011-10-06 21:36:39,297 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCElasticConstants', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ar', info:UnboundLocalError("local variable 'testObject' referenced before assignment",)
2011-10-06 21:36:39,298 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 56, in run_test
    del testObject
UnboundLocalError: local variable 'testObject' referenced before assignment

2011-10-06 21:36:39,299 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.05302906036376953 seconds
2011-10-06 21:36:39,299 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ne'
2011-10-06 21:36:39,299 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCElasticConstants',potential='model_ArNe_P_MLJ_NEIGH_RVEC_F',element='Ne'
2011-10-06 21:36:39,300 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,300 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,301 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCLattice',potential='model_ArNe_P_MLJ_NEIGH_RVEC_F',element='Ne'
2011-10-06 21:36:39,301 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,302 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,302 - openkimtests.Test.FCCLattice - DEBUG - Recieved a main method call
2011-10-06 21:36:39,302 - openkimtests.Test.FCCLattice - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,303 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,303 - openkimtests.potential - DEBUG - potentialname: model_ArNe_P_MLJ_NEIGH_RVEC_F found
2011-10-06 21:36:39,303 - openkimtests.potential - DEBUG - element 'Ne' found
2011-10-06 21:36:39,357 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCElasticConstants', potential='model_ArNe_P_MLJ_NEIGH_RVEC_F', element='Ne', info:UnboundLocalError("local variable 'testObject' referenced before assignment",)
2011-10-06 21:36:39,358 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 56, in run_test
    del testObject
UnboundLocalError: local variable 'testObject' referenced before assignment

2011-10-06 21:36:39,358 - openkimtests.pipeline.run_tests - INFO - Element 'Ne' Run took 0.059092044830322266 seconds
2011-10-06 21:36:39,358 - openkimtests.pipeline.run_tests - INFO - Potential 'model_ArNe_P_MLJ_NEIGH_RVEC_F' run took 0.11300802230834961 seconds
2011-10-06 21:36:39,359 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MLJ_CLUSTER_C'
2011-10-06 21:36:39,359 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:39,360 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCElasticConstants',potential='model_Ar_P_MLJ_CLUSTER_C',element='Ar'
2011-10-06 21:36:39,360 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,360 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,361 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCLattice',potential='model_Ar_P_MLJ_CLUSTER_C',element='Ar'
2011-10-06 21:36:39,362 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,362 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,363 - openkimtests.Test.FCCLattice - DEBUG - Recieved a main method call
2011-10-06 21:36:39,363 - openkimtests.Test.FCCLattice - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,363 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,364 - openkimtests.potential - DEBUG - potentialname: model_Ar_P_MLJ_CLUSTER_C found
2011-10-06 21:36:39,364 - openkimtests.potential - DEBUG - element 'Ar' found
2011-10-06 21:36:39,392 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCElasticConstants', potential='model_Ar_P_MLJ_CLUSTER_C', element='Ar', info:UnboundLocalError("local variable 'testObject' referenced before assignment",)
2011-10-06 21:36:39,393 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 56, in run_test
    del testObject
UnboundLocalError: local variable 'testObject' referenced before assignment

2011-10-06 21:36:39,394 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.03425908088684082 seconds
2011-10-06 21:36:39,394 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MLJ_CLUSTER_C' run took 0.0346829891204834 seconds
2011-10-06 21:36:39,394 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MLJ_NEIGH_PURE_H_F'
2011-10-06 21:36:39,395 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:39,395 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCElasticConstants',potential='model_Ar_P_MLJ_NEIGH_PURE_H_F',element='Ar'
2011-10-06 21:36:39,395 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,396 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,397 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCLattice',potential='model_Ar_P_MLJ_NEIGH_PURE_H_F',element='Ar'
2011-10-06 21:36:39,397 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,398 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,398 - openkimtests.Test.FCCLattice - DEBUG - Recieved a main method call
2011-10-06 21:36:39,399 - openkimtests.Test.FCCLattice - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,399 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,399 - openkimtests.potential - DEBUG - potentialname: model_Ar_P_MLJ_NEIGH_PURE_H_F found
2011-10-06 21:36:39,399 - openkimtests.potential - DEBUG - element 'Ar' found
2011-10-06 21:36:39,439 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCElasticConstants', potential='model_Ar_P_MLJ_NEIGH_PURE_H_F', element='Ar', info:UnboundLocalError("local variable 'testObject' referenced before assignment",)
2011-10-06 21:36:39,440 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 56, in run_test
    del testObject
UnboundLocalError: local variable 'testObject' referenced before assignment

2011-10-06 21:36:39,441 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.04603004455566406 seconds
2011-10-06 21:36:39,441 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MLJ_NEIGH_PURE_H_F' run took 0.04643988609313965 seconds
2011-10-06 21:36:39,441 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MMorse'
2011-10-06 21:36:39,442 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:39,442 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCElasticConstants',potential='model_Ar_P_MMorse',element='Ar'
2011-10-06 21:36:39,443 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,443 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,444 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:39,445 - openkimtests.Test.FCCElasticConstants - DEBUG - Recieved a main method call
2011-10-06 21:36:39,446 - openkimtests.Test.FCCElasticConstants - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,446 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,447 - openkimtests.potential - DEBUG - potentialname: model_Ar_P_MMorse found
2011-10-06 21:36:39,447 - openkimtests.potential - DEBUG - element 'Ar' found
2011-10-06 21:36:39,484 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCElasticConstants', potential='model_Ar_P_MMorse', element='Ar', info:OSError(24, 'Too many open files')
2011-10-06 21:36:39,486 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCElasticConstants.py", line 63, in results
    elastic_constants = hess(sp.zeros(6))
  File "/usr/local/pub/lib/python2.7/site-packages/Numdifftools-0.3.5-py2.7.egg/numdifftools/core.py", line 1202, in __call__
    return self._hessian(x00)
  File "/usr/local/pub/lib/python2.7/site-packages/Numdifftools-0.3.5-py2.7.egg/numdifftools/core.py", line 819, in _hessian
    hess = self._hessdiag(x00)
  File "/usr/local/pub/lib/python2.7/site-packages/Numdifftools-0.3.5-py2.7.egg/numdifftools/core.py", line 807, in _hessdiag
    return self._partial_der(x00)
  File "/usr/local/pub/lib/python2.7/site-packages/Numdifftools-0.3.5-py2.7.egg/numdifftools/core.py", line 780, in _partial_der
    PD[ind] = self._derivative(x0[ind], stepNom[ind])
  File "/usr/local/pub/lib/python2.7/site-packages/Numdifftools-0.3.5-py2.7.egg/numdifftools/core.py", line 708, in _derivative
    f_x0[j] = self.fun(x0j)
  File "/usr/local/pub/lib/python2.7/site-packages/Numdifftools-0.3.5-py2.7.egg/numdifftools/core.py", line 792, in _fun
    return  self.fun_org(x)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCElasticConstants.py", line 54, in strain
    energy = self.slab.get_potential_energy()
  File "/usr/local/pub/lib/python2.7/site-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 200, in run
    stdin=PIPE, stdout=PIPE)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 1035, in _get_handles
    p2cread, p2cwrite = os.pipe()
OSError: [Errno 24] Too many open files

2011-10-06 21:36:39,487 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.04524993896484375 seconds
2011-10-06 21:36:39,487 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MMorse' run took 0.045658111572265625 seconds
2011-10-06 21:36:39,487 - openkimtests.pipeline.run_tests - INFO - Test 'FCCElasticConstants' run took 0.04587697982788086 seconds
2011-10-06 21:36:39,488 - openkimtests.pipeline.run_tests - INFO - 
Running tests for test='FCCVacancy'
2011-10-06 21:36:39,488 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Al_PF_ErcolessiAdams'
2011-10-06 21:36:39,488 - openkimtests.pipeline.run_tests - INFO - 
Running element='Al'
2011-10-06 21:36:39,489 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='model_Al_PF_ErcolessiAdams',element='Al'
2011-10-06 21:36:39,489 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,490 - openkimtests.pipeline.runtest - ERROR - openkimtests.kim_tests.'FCCVacancy' failed to import
2011-10-06 21:36:39,493 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='model_Al_PF_ErcolessiAdams', element='Al', info:UnboundLocalError("local variable 'testObject' referenced before assignment",)
2011-10-06 21:36:39,494 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 56, in run_test
    del testObject
UnboundLocalError: local variable 'testObject' referenced before assignment

2011-10-06 21:36:39,494 - openkimtests.pipeline.run_tests - INFO - Element 'Al' Run took 0.0059168338775634766 seconds
2011-10-06 21:36:39,495 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Al_PF_ErcolessiAdams' run took 0.0063250064849853516 seconds
2011-10-06 21:36:39,495 - openkimtests.pipeline.run_tests - INFO - 
Running potential='ASAP'
2011-10-06 21:36:39,495 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ni'
2011-10-06 21:36:39,496 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='ASAP',element='Ni'
2011-10-06 21:36:39,496 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,498 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,498 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:39,499 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:39,514 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,514 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,515 - openkimtests.potential - DEBUG - potentialname: ASAP found
2011-10-06 21:36:39,515 - openkimtests.potential - DEBUG - element 'Ni' found
2011-10-06 21:36:39,528 - openkimtests.potential.ASAP_loader - WARNING - ASAP package could not be loaded
2011-10-06 21:36:39,529 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='ASAP', element='Ni', info:PackageDoesNotExist('ASAP',)
2011-10-06 21:36:39,530 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 22, in results
    self.slab.set_calculator(self.calculator)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 59, in calculator
    self.slab)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 238, in load
    return potentials[name](name,element,slab,*args,**kwargs)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 79, in ASAP_loader
    raise PackageDoesNotExist('ASAP')
PackageDoesNotExist: ASAP

2011-10-06 21:36:39,531 - openkimtests.pipeline.run_tests - INFO - Element 'Ni' Run took 0.03519892692565918 seconds
2011-10-06 21:36:39,531 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ag'
2011-10-06 21:36:39,531 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='ASAP',element='Ag'
2011-10-06 21:36:39,532 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,532 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,532 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:39,533 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:39,545 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,545 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,546 - openkimtests.potential - DEBUG - potentialname: ASAP found
2011-10-06 21:36:39,546 - openkimtests.potential - DEBUG - element 'Ag' found
2011-10-06 21:36:39,555 - openkimtests.potential.ASAP_loader - WARNING - ASAP package could not be loaded
2011-10-06 21:36:39,555 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='ASAP', element='Ag', info:PackageDoesNotExist('ASAP',)
2011-10-06 21:36:39,556 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 22, in results
    self.slab.set_calculator(self.calculator)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 59, in calculator
    self.slab)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 238, in load
    return potentials[name](name,element,slab,*args,**kwargs)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 79, in ASAP_loader
    raise PackageDoesNotExist('ASAP')
PackageDoesNotExist: ASAP

2011-10-06 21:36:39,557 - openkimtests.pipeline.run_tests - INFO - Element 'Ag' Run took 0.025905847549438477 seconds
2011-10-06 21:36:39,557 - openkimtests.pipeline.run_tests - INFO - 
Running element='Pt'
2011-10-06 21:36:39,557 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='ASAP',element='Pt'
2011-10-06 21:36:39,558 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,558 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,558 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:39,559 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:39,575 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,576 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,576 - openkimtests.potential - DEBUG - potentialname: ASAP found
2011-10-06 21:36:39,576 - openkimtests.potential - DEBUG - element 'Pt' found
2011-10-06 21:36:39,586 - openkimtests.potential.ASAP_loader - WARNING - ASAP package could not be loaded
2011-10-06 21:36:39,587 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='ASAP', element='Pt', info:PackageDoesNotExist('ASAP',)
2011-10-06 21:36:39,588 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 22, in results
    self.slab.set_calculator(self.calculator)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 59, in calculator
    self.slab)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 238, in load
    return potentials[name](name,element,slab,*args,**kwargs)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 79, in ASAP_loader
    raise PackageDoesNotExist('ASAP')
PackageDoesNotExist: ASAP

2011-10-06 21:36:39,589 - openkimtests.pipeline.run_tests - INFO - Element 'Pt' Run took 0.03183102607727051 seconds
2011-10-06 21:36:39,589 - openkimtests.pipeline.run_tests - INFO - 
Running element='Au'
2011-10-06 21:36:39,590 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='ASAP',element='Au'
2011-10-06 21:36:39,590 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,591 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,591 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:39,592 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:39,608 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,608 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,608 - openkimtests.potential - DEBUG - potentialname: ASAP found
2011-10-06 21:36:39,609 - openkimtests.potential - DEBUG - element 'Au' found
2011-10-06 21:36:39,617 - openkimtests.potential.ASAP_loader - WARNING - ASAP package could not be loaded
2011-10-06 21:36:39,617 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='ASAP', element='Au', info:PackageDoesNotExist('ASAP',)
2011-10-06 21:36:39,618 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 22, in results
    self.slab.set_calculator(self.calculator)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 59, in calculator
    self.slab)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 238, in load
    return potentials[name](name,element,slab,*args,**kwargs)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 79, in ASAP_loader
    raise PackageDoesNotExist('ASAP')
PackageDoesNotExist: ASAP

2011-10-06 21:36:39,619 - openkimtests.pipeline.run_tests - INFO - Element 'Au' Run took 0.029375076293945312 seconds
2011-10-06 21:36:39,619 - openkimtests.pipeline.run_tests - INFO - 
Running element='Pd'
2011-10-06 21:36:39,619 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='ASAP',element='Pd'
2011-10-06 21:36:39,620 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,620 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,620 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:39,621 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:39,637 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,638 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,638 - openkimtests.potential - DEBUG - potentialname: ASAP found
2011-10-06 21:36:39,638 - openkimtests.potential - DEBUG - element 'Pd' found
2011-10-06 21:36:39,648 - openkimtests.potential.ASAP_loader - WARNING - ASAP package could not be loaded
2011-10-06 21:36:39,649 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='ASAP', element='Pd', info:PackageDoesNotExist('ASAP',)
2011-10-06 21:36:39,650 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 22, in results
    self.slab.set_calculator(self.calculator)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 59, in calculator
    self.slab)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 238, in load
    return potentials[name](name,element,slab,*args,**kwargs)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/potential.py", line 79, in ASAP_loader
    raise PackageDoesNotExist('ASAP')
PackageDoesNotExist: ASAP

2011-10-06 21:36:39,651 - openkimtests.pipeline.run_tests - INFO - Element 'Pd' Run took 0.03195691108703613 seconds
2011-10-06 21:36:39,652 - openkimtests.pipeline.run_tests - INFO - Test 'FCCVacancy','ASAP','Cu' exists
2011-10-06 21:36:39,653 - openkimtests.pipeline.run_tests - INFO - Unessesary test 'FCCVacancy','ASAP','Cu'
2011-10-06 21:36:39,653 - openkimtests.pipeline.run_tests - INFO - Potential 'ASAP' run took 0.15749907493591309 seconds
2011-10-06 21:36:39,653 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ne_P_LJ_NEIGH_PURE_H'
2011-10-06 21:36:39,654 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ne'
2011-10-06 21:36:39,654 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='model_Ne_P_LJ_NEIGH_PURE_H',element='Ne'
2011-10-06 21:36:39,654 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:39,655 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:39,656 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:39,656 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:39,672 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:39,673 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:39,673 - openkimtests.potential - DEBUG - potentialname: model_Ne_P_LJ_NEIGH_PURE_H found
2011-10-06 21:36:39,673 - openkimtests.potential - DEBUG - element 'Ne' found
2011-10-06 21:36:40,068 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='model_Ne_P_LJ_NEIGH_PURE_H', element='Ne', info:OSError(24, 'Too many open files')
2011-10-06 21:36:40,069 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 24, in results
    energy1 = self.slab.get_potential_energy()
  File "/usr/local/pub/lib/python2.7/site-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 200, in run
    stdin=PIPE, stdout=PIPE)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 1035, in _get_handles
    p2cread, p2cwrite = os.pipe()
OSError: [Errno 24] Too many open files

2011-10-06 21:36:40,070 - openkimtests.pipeline.run_tests - INFO - Element 'Ne' Run took 0.4159719944000244 seconds
2011-10-06 21:36:40,070 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ne_P_LJ_NEIGH_PURE_H' run took 0.41629791259765625 seconds
2011-10-06 21:36:40,070 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MLJ_C'
2011-10-06 21:36:40,070 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:40,071 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='model_Ar_P_MLJ_C',element='Ar'
2011-10-06 21:36:40,071 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:40,071 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:40,072 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:40,072 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:40,072 - openkimtests.db - WARNING - Request 'FCCLattice.model_Ar_P_MLJ_C.Ar.xml' doesn't exist
2011-10-06 21:36:40,117 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='model_Ar_P_MLJ_C', element='Ar', info:IOError(24, 'Too many open files')
2011-10-06 21:36:40,119 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 16, in results
    a = request(self.potentialname,self.element,'FCCLattice','FCCLatticeConstant')
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/pipeline.py", line 152, in request
    ans = db.request(potential,element,test,resultentry)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/db.py", line 187, in request
    test=test)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/db.py", line 42, in XMLReader
    tree = etree.parse(os.path.join(results_dir,filename))
  File "/usr/local/pub/lib/python2.7/xml/etree/ElementTree.py", line 1177, in parse
    tree.parse(source, parser)
  File "/usr/local/pub/lib/python2.7/xml/etree/ElementTree.py", line 646, in parse
    source = open(source, "rb")
IOError: [Errno 24] Too many open files: '/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/results/FCCLattice.model_Ar_P_MLJ_C.Ar.xml'

2011-10-06 21:36:40,120 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.04965686798095703 seconds
2011-10-06 21:36:40,120 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MLJ_C' run took 0.050065040588378906 seconds
2011-10-06 21:36:40,121 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ne_P_MLJ_NEIGH_RVEC_F'
2011-10-06 21:36:40,121 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ne'
2011-10-06 21:36:40,121 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='model_Ne_P_MLJ_NEIGH_RVEC_F',element='Ne'
2011-10-06 21:36:40,122 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:40,122 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:40,123 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:40,123 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:40,140 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:40,140 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:40,140 - openkimtests.potential - DEBUG - potentialname: model_Ne_P_MLJ_NEIGH_RVEC_F found
2011-10-06 21:36:40,141 - openkimtests.potential - DEBUG - element 'Ne' found
2011-10-06 21:36:40,452 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='model_Ne_P_MLJ_NEIGH_RVEC_F', element='Ne', info:OSError(24, 'Too many open files')
2011-10-06 21:36:40,454 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 24, in results
    energy1 = self.slab.get_potential_energy()
  File "/usr/local/pub/lib/python2.7/site-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 200, in run
    stdin=PIPE, stdout=PIPE)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 1035, in _get_handles
    p2cread, p2cwrite = os.pipe()
OSError: [Errno 24] Too many open files

2011-10-06 21:36:40,454 - openkimtests.pipeline.run_tests - INFO - Element 'Ne' Run took 0.33325910568237305 seconds
2011-10-06 21:36:40,454 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ne_P_MLJ_NEIGH_RVEC_F' run took 0.3336141109466553 seconds
2011-10-06 21:36:40,455 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MLJ_F90'
2011-10-06 21:36:40,455 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:40,455 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='model_Ar_P_MLJ_F90',element='Ar'
2011-10-06 21:36:40,456 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:40,456 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:40,456 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:40,457 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:40,457 - openkimtests.db - WARNING - Request 'FCCLattice.model_Ar_P_MLJ_F90.Ar.xml' doesn't exist
2011-10-06 21:36:40,515 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='model_Ar_P_MLJ_F90', element='Ar', info:IOError(24, 'Too many open files')
2011-10-06 21:36:40,516 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 16, in results
    a = request(self.potentialname,self.element,'FCCLattice','FCCLatticeConstant')
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/pipeline.py", line 152, in request
    ans = db.request(potential,element,test,resultentry)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/db.py", line 187, in request
    test=test)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/db.py", line 42, in XMLReader
    tree = etree.parse(os.path.join(results_dir,filename))
  File "/usr/local/pub/lib/python2.7/xml/etree/ElementTree.py", line 1177, in parse
    tree.parse(source, parser)
  File "/usr/local/pub/lib/python2.7/xml/etree/ElementTree.py", line 646, in parse
    source = open(source, "rb")
IOError: [Errno 24] Too many open files: '/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/results/FCCLattice.model_Ar_P_MLJ_F90.Ar.xml'

2011-10-06 21:36:40,517 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.06194496154785156 seconds
2011-10-06 21:36:40,517 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MLJ_F90' run took 0.06231689453125 seconds
2011-10-06 21:36:40,517 - openkimtests.pipeline.run_tests - INFO - 
Running potential='model_Ar_P_MLJ_MI_OPBC_H_F'
2011-10-06 21:36:40,518 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ar'
2011-10-06 21:36:40,518 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='model_Ar_P_MLJ_MI_OPBC_H_F',element='Ar'
2011-10-06 21:36:40,519 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:40,519 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:40,520 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:40,520 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCLattice',potential='model_Ar_P_MLJ_MI_OPBC_H_F',element='Ar'
2011-10-06 21:36:40,521 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:40,521 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:40,522 - openkimtests.Test.FCCLattice - DEBUG - Recieved a main method call
2011-10-06 21:36:40,522 - openkimtests.Test.FCCLattice - DEBUG - Recieved a calculator access call
2011-10-06 21:36:40,522 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:40,523 - openkimtests.potential - DEBUG - potentialname: model_Ar_P_MLJ_MI_OPBC_H_F found
2011-10-06 21:36:40,523 - openkimtests.potential - DEBUG - element 'Ar' found
2011-10-06 21:36:40,590 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='model_Ar_P_MLJ_MI_OPBC_H_F', element='Ar', info:OSError(24, 'Too many open files')
2011-10-06 21:36:40,592 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 16, in results
    a = request(self.potentialname,self.element,'FCCLattice','FCCLatticeConstant')
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/pipeline.py", line 150, in request
    run_test(test,potential,element)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCLattice.py", line 43, in results
    minimum, energyminimum, iterations, funcalls, warnflag = fmin(self.FCCEnergy,x0,full_output=1,disp=0)
  File "/usr/local/pub/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 278, in fmin
    fsim[0] = func(x0)
  File "/usr/local/pub/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 176, in function_wrapper
    return function(x, *args)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCLattice.py", line 30, in FCCEnergy
    return self.slab.get_potential_energy()
  File "/usr/local/pub/lib/python2.7/site-packages/ase/atoms.py", line 548, in get_potential_energy
    return self._calc.get_potential_energy(self)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 118, in get_potential_energy
    self.update(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 134, in update
    self.calculate(atoms)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 138, in calculate
    self.run()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/kim.py", line 200, in run
    stdin=PIPE, stdout=PIPE)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/local/pub/lib/python2.7/subprocess.py", line 1035, in _get_handles
    p2cread, p2cwrite = os.pipe()
OSError: [Errno 24] Too many open files

2011-10-06 21:36:40,593 - openkimtests.pipeline.run_tests - INFO - Element 'Ar' Run took 0.07540416717529297 seconds
2011-10-06 21:36:40,594 - openkimtests.pipeline.run_tests - INFO - Potential 'model_Ar_P_MLJ_MI_OPBC_H_F' run took 0.07580900192260742 seconds
2011-10-06 21:36:40,594 - openkimtests.pipeline.run_tests - INFO - 
Running potential='EMT'
2011-10-06 21:36:40,594 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ni'
2011-10-06 21:36:40,595 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='EMT',element='Ni'
2011-10-06 21:36:40,595 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:40,596 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:40,596 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:40,597 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:40,597 - openkimtests.db - WARNING - Request 'FCCLattice.EMT.Ni.xml' doesn't exist
2011-10-06 21:36:40,600 - openkimtests.pipeline.run_tests - ERROR - 
ERROR on test='FCCVacancy', potential='EMT', element='Ni', info:IOError(24, 'Too many open files')
2011-10-06 21:36:40,601 - openkimtests.pipeline.run_tests - ERROR - TRACEBACK: Traceback (most recent call last):
  File "pipeline.py", line 126, in run_tests
    verbose=verbose)
  File "pipeline.py", line 51, in run_test
    results = testObject.main()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/_BaseTest.py", line 83, in main
    results = self.results()
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/kim_tests/FCCVacancy.py", line 16, in results
    a = request(self.potentialname,self.element,'FCCLattice','FCCLatticeConstant')
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/pipeline.py", line 152, in request
    ans = db.request(potential,element,test,resultentry)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/db.py", line 187, in request
    test=test)
  File "/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/bin/db.py", line 42, in XMLReader
    tree = etree.parse(os.path.join(results_dir,filename))
  File "/usr/local/pub/lib/python2.7/xml/etree/ElementTree.py", line 1177, in parse
    tree.parse(source, parser)
  File "/usr/local/pub/lib/python2.7/xml/etree/ElementTree.py", line 646, in parse
    source = open(source, "rb")
IOError: [Errno 24] Too many open files: '/afs/msc.cornell.edu/home/jsethna/alemi/openkimtests/results/FCCLattice.EMT.Ni.xml'

2011-10-06 21:36:40,602 - openkimtests.pipeline.run_tests - INFO - Element 'Ni' Run took 0.007708072662353516 seconds
2011-10-06 21:36:40,602 - openkimtests.pipeline.run_tests - INFO - 
Running element='C'
2011-10-06 21:36:40,603 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='EMT',element='C'
2011-10-06 21:36:40,603 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:36:40,604 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:36:40,604 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:36:40,605 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:36:40,618 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:36:40,618 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:36:40,619 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:36:40,619 - openkimtests.potential - DEBUG - element 'C' found
2011-10-06 21:37:05,277 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:37:05,277 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:37:05,277 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:37:05,277 - openkimtests.potential - DEBUG - element 'C' found
2011-10-06 21:44:46,316 - openkimtests.db.XMLWriter - DEBUG - XMLWriter called.
2011-10-06 21:44:46,396 - openkimtests.pipeline.runtest - INFO - Computed results, obtained: {'NAtoms': 2048, 'VacancyFormationEnergy': 0.1125701486841848}

2011-10-06 21:44:46,399 - openkimtests.pipeline.run_tests - INFO - Element 'C' Run took 485.7961709499359 seconds
2011-10-06 21:44:46,399 - openkimtests.pipeline.run_tests - INFO - 
Running element='Pt'
2011-10-06 21:44:46,399 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='EMT',element='Pt'
2011-10-06 21:44:46,400 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:44:46,400 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:44:46,401 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:44:46,403 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:44:46,483 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:44:46,483 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:44:46,483 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:44:46,483 - openkimtests.potential - DEBUG - element 'Pt' found
2011-10-06 21:44:56,735 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:44:56,735 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:44:56,735 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:44:56,736 - openkimtests.potential - DEBUG - element 'Pt' found
2011-10-06 21:46:16,864 - openkimtests.db.XMLWriter - DEBUG - XMLWriter called.
2011-10-06 21:46:16,938 - openkimtests.pipeline.runtest - INFO - Computed results, obtained: {'NAtoms': 2048, 'VacancyFormationEnergy': 1.0196849522903055}

2011-10-06 21:46:16,940 - openkimtests.pipeline.run_tests - INFO - Element 'Pt' Run took 90.54105305671692 seconds
2011-10-06 21:46:16,941 - openkimtests.pipeline.run_tests - INFO - 
Running element='Ag'
2011-10-06 21:46:16,941 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='EMT',element='Ag'
2011-10-06 21:46:16,941 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:46:16,942 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:46:16,942 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:46:16,944 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:46:16,988 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:46:16,988 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:46:16,989 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:46:16,989 - openkimtests.potential - DEBUG - element 'Ag' found
2011-10-06 21:46:27,209 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:46:27,209 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:46:27,209 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:46:27,209 - openkimtests.potential - DEBUG - element 'Ag' found
2011-10-06 21:47:09,932 - openkimtests.db.XMLWriter - DEBUG - XMLWriter called.
2011-10-06 21:47:09,954 - openkimtests.pipeline.runtest - INFO - Computed results, obtained: {'NAtoms': 2048, 'VacancyFormationEnergy': 0.8514235144191201}

2011-10-06 21:47:09,955 - openkimtests.pipeline.run_tests - INFO - Element 'Ag' Run took 53.01446890830994 seconds
2011-10-06 21:47:09,956 - openkimtests.pipeline.run_tests - INFO - 
Running element='H'
2011-10-06 21:47:09,956 - openkimtests.pipeline.runtest - INFO - 
About to run a test, test='FCCVacancy',potential='EMT',element='H'
2011-10-06 21:47:09,956 - openkimtests.pipeline.runtest - INFO - Attempting to load the test
2011-10-06 21:47:09,957 - openkimtests.pipeline.runtest - INFO - Creating a test instance
2011-10-06 21:47:09,957 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a main method call
2011-10-06 21:47:09,958 - openkimtests.db.XMLReader - DEBUG - XMLReader called...
2011-10-06 21:47:10,001 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:47:10,001 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:47:10,001 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:47:10,001 - openkimtests.potential - DEBUG - element 'H' found
2011-10-06 21:48:18,680 - openkimtests.Test.FCCVacancy - DEBUG - Recieved a calculator access call
2011-10-06 21:48:18,680 - openkimtests.potential - DEBUG - Recieved a potential.load call
2011-10-06 21:48:18,680 - openkimtests.potential - DEBUG - potentialname: EMT found
2011-10-06 21:48:18,680 - openkimtests.potential - DEBUG - element 'H' found
